namespace Quester
{
    internal enum LocationType
    {
        None = -1,
        Alchemist,
        HouseForSale,
        Armorer,
        Bank,
        Town4,
        Bookseller,
        ClothingStore,
        FurnitureStore,
        GemStore,
        GeneralStore,
        Library,
        GuildHall,
        PawnShop,
        WeaponSmith,
        Temple,
        Tavern,
        Palace,
        House1,
        House2,
        House3,
        House4,
        House5,
        House6,
        Town23,
        Ship,
        Dungeon = 499,
        Crypt = 500,
        OrcStronghold = 501,
        HumanStronghold = 502,
        Prison = 503,
        DesecratedTemple = 504,
        Mine = 505,
        NaturalCave = 506,
        Coven = 507,
        VampireHaunt = 508,
        Laboratory = 509,
        HarpyNest = 510,
        RuinedCastle = 511,
        SpiderNest = 512,
        GiantStronghold = 513,
        DragonsDen = 514,
        BarbarianStronghold = 515,
        VolcanicCaves = 516,
        ScorpionNest = 517,
        Cemetery = 518,
        NoDungeon = 755,
        SpecificLocation = 666,
        Special1 = 116,
        Special2 = 223,
        Special3 = 249,
        Special4 = 250,
        AnyHouse = 0xfffe,
        AllValid = 0xffff
    }
}